# Generated by Django 5.2.5 on 2026-09-15 07:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0005_profile_activity_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="leaderboard_entry",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("daily_points", models.IntegerField(default=0)),
                ("weekly_points", models.IntegerField(default=0)),
                ("monthly_points", models.IntegerField(default=0)),
                ("total_points", models.IntegerField(default=0)),
                ("last_post_date", models.DateField(blank=True, null=True)),
                ("consecutive_post_days", models.IntegerField(default=0)),
                (
                    "daily_updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "weekly_updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "monthly_updated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Leaderboard Entry",
                "verbose_name_plural": "Leaderboard Entries",
                "ordering": ["-total_points"],
            },
        ),
        migrations.CreateModel(
            name="CodingProblemPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code_snippet", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("PYTHON", "Python"),
                            ("CPP", "C++"),
                            ("JAVA", "Java"),
                            ("JAVASCRIPT", "JavaScript"),
                            ("TYPESCRIPT", "TypeScript"),
                        ],
                        default="PYTHON",
                        max_length=20,
                    ),
                ),
                (
                    "time_complexity",
                    models.CharField(
                        choices=[
                            ("O(1)", "O(1) - Constant"),
                            ("O(log n)", "O(log n) - Logarithmic"),
                            ("O(n)", "O(n) - Linear"),
                            ("O(n log n)", "O(n log n) - Log-Linear"),
                            ("O(n^2)", "O(n^2) - Quadratic"),
                            ("O(n^3)", "O(n^3) - Cubic"),
                            ("O(2^n)", "O(2^n) - Exponential"),
                            ("O(n!)", "O(n!) - Factorial"),
                        ],
                        default="O(n)",
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("points_earned", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coding Problem Post",
                "verbose_name_plural": "Coding Problem Posts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="dsa_codingp_created_69e237_idx"
                    ),
                    models.Index(
                        fields=["author", "-created_at"],
                        name="dsa_codingp_author__023774_idx",
                    ),
                ],
            },
        ),
    ]
